import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";

const myLocal = localFont({
  src: "../fonts/norwester.otf",
});

export const metadata: Metadata = {
  title: "Wassp Multibeam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={myLocal.className}>
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  );
}
